### ISSUE TITLE
Allow the issue or pull request author to be referenced in the `-msg` inputs

### ISSUE THREAD

**Issue by plbstl** [plbstl/first-contribution#13]
This helps when symlink -ing message inputs. So the author stays consistent regardless of if it is an issue or pull request.

From the detailed example in the readme:

```yaml
# New pull request is OPENED.
pr-opened-msg: issue-opened-msg
# Authored pull request is MERGED.
pr-merged-msg: issue-completed-msg
# Authored pull request is CLOSED without being merged.
pr-closed-msg: issue-not-planned-msg
# messages
issue-opened-msg: |
  ### Hey @${{ github.actor }}!

  Looks like it's your first time interacting with (Project Name) here on GitHub.

  Welcome and thank you for taking the time to report an issue :heart:.

  Please check out our [code of conduct](https://github.com/user/repo/blob/main/CODE_OF_CONDUCT.md) and [contribution guide](https://github.com/user/repo/blob/main/CONTRIBUTING.md) to learn how to interact with and contribute to the community.

  Don't forget to star :star: the repo.
issue-completed-msg: |
  ### Hey @${{ github.event.issue.user.login }}!

  Thank you for your contribution, feel free to come by anytime.
issue-not-planned-msg: |
  ### Hey @${{ github.event.issue.user.login }}!

  Thank you for taking the time to make a contribution, don't let this stop you from reaching out again.
```

The `pr-*-msg` inputs will not have access to `github.event.issue.user.login`
